token:
  secret: f2c370d229e746459e1f6b373bd2bfd5
  access:
    name: Access-Token
    expired-time: 3600
    expired-time-milli: 3600000
  refresh:
    name: Refresh-Token
    expired-time: 1209600
    expired-time-milli: 1209600000

cors:
  allow-origins:
    - https://i7a504.p.ssafy.io
    - http://i7a504.p.ssafy.io
    - http://localhost:3000

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: f7f0ef574cef898392f2817ec06357c5
            redirect-uri: https://i7a504.p.ssafy.io/oauth2/code/kakao
#            redirect-uri: http://localhost:8080/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
