spring:
  datasource:
    url: jdbc:mysql://i7a504.p.ssafy.io:3741/a504?allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: xBpIRi%O1q
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        default_batch_fetch_size: 100

# server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: Z5sx8Fkr
#    key-store-type: PKCS12
